
name: Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install

      - name: Publish
        run: npx vsce publish -p ${{ secrets.AZURE_TOKEN }}